from typing import Any, Protocol, TypeVar

from enums import OrderType
from .orders import Order
from .typing import EnginePayload, MatchResult, CancelRequest, ModifyRequest

T = TypeVar("T")


class PayloadProtocol(Protocol):
    @property
    def payload(self) -> dict: ...

    def apply_fill(self, quantity: int, price: float) -> None: ...

    def apply_cancel(self, quantity: int) -> None: ...


class StoreProtocol(Protocol):
    def add(self, value) -> None: ...

    def remove(self, value) -> None: ...

    def get(self, value) -> Any: ...


class EngineProtocol(Protocol):

    def place_order(self, payload: EnginePayload) -> None: ...

    def cancel_order(self, request: CancelRequest) -> None: ...

    def modify_order(self, request: ModifyRequest) -> None: ...

    def _create_payload(
        self, payload: dict, internal_type: OrderType
    ) -> PayloadProtocol: ...

    def _build_context(self, payload: PayloadProtocol): ...

    def _execute_match(
        self, order: Order, payload: PayloadProtocol, context: "OrderContext"
    ) -> MatchResult: ...

    def _add_to_store(self, order: Order, internal_type: OrderType) -> None: ...


class BalanceManagerProtocol(Protocol):
    def append(self, db_payload: dict) -> None: ...

    def remove(self, db_payload: dict) -> None: ...

    def get_balance(self, db_payload: dict) -> int: ...

    def increase_balance(self, db_payload: dict, quantity: int): ...

    def decrease_balance(self, db_payload: dict, quantity: int): ...
