"""added closed at and close price

Revision ID: 003aca5c4a8f
Revises: be9a7d80a883
Create Date: 2024-11-03 20:24:46.325940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003aca5c4a8f'
down_revision: Union[str, None] = 'be9a7d80a883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('close_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'close_price')
    # ### end Alembic commands ###
