"""defaul order status NOT FILLED

Revision ID: 029c08d2a17e
Revises: 0875735f0ebf
Create Date: 2024-10-31 17:06:34.011576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029c08d2a17e'
down_revision: Union[str, None] = '0875735f0ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
