"""Added 2 fields: market_type, side

Revision ID: 05c93b13f41a
Revises: ea9126b5c84a
Create Date: 2025-01-05 02:24:48.169136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c93b13f41a'
down_revision: Union[str, None] = 'ea9126b5c84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders', 
        sa.Column(
            'market_type', 
            sa.Enum('FUTURES', 'SPOT', name='market_type'), 
            nullable=True,
            default='SPOT',
        )
    )
    op.add_column(
        'orders', 
        sa.Column(
            'side', 
            sa.Enum('LONG', 'SHORT', name='side'), 
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    - DROP TYPE market_type
    - DROP TYPE side
    """
    op.drop_column('orders', 'side')
    op.drop_column('orders', 'market_type')
    # ### end Alembic commands ###
