"""added fields

Revision ID: 0875735f0ebf
Revises: 9d34038621e0
Create Date: 2024-10-31 17:02:31.145217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from enums import OrderStatus

# revision identifiers, used by Alembic.
revision: str = '0875735f0ebf'
down_revision: Union[str, None] = '9d34038621e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    order_status_enum = sa.Enum(OrderStatus, name="order_status")
    order_status_enum.create(op.get_bind())
    op.add_column('orders', sa.Column('order_status', sa.Enum('FILLED', 'PARTIALLY_FILLED', 'NOT_FILLED', name='order_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_status')
    order_status_enum = sa.Enum(OrderStatus, name="order_status")
    order_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
