"""changed dollar amount to quantity

Revision ID: 0fd66c8ea319
Revises: c939c19552c4
Create Date: 2024-10-30 11:23:25.018454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd66c8ea319'
down_revision: Union[str, None] = 'c939c19552c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Float(), nullable=False))
    op.drop_column('orders', 'dollar_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('dollar_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
