"""added closed price to orders

Revision ID: 1fb1906b0865
Revises: a6d62cc1cbdb
Create Date: 2025-03-02 16:39:04.520301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb1906b0865'
down_revision: Union[str, None] = 'a6d62cc1cbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('closed_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'closed_price')
    # ### end Alembic commands ###
