"""removed unique constraint on avatar

Revision ID: 33e2d0d5273c
Revises: cec5f4695164
Create Date: 2025-02-27 21:35:37.176523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e2d0d5273c'
down_revision: Union[str, None] = 'cec5f4695164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_avatar_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_avatar_key', 'users', ['avatar'])
    # ### end Alembic commands ###
