"""unique master and watcher pair on UserWatchlist

Revision ID: 53b6cca58e7a
Revises: 7f5df52ba92a
Create Date: 2024-12-06 21:49:16.286222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b6cca58e7a'
down_revision: Union[str, None] = '7f5df52ba92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unq_master_watcher', 'watchlist_user', ['master', 'watcher'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_master_watcher', 'watchlist_user', type_='unique')
    # ### end Alembic commands ###
