"""updated quantity to integer and not null, added standing quantity field

Revision ID: 5449b2a706d8
Revises: feac743d4799
Create Date: 2024-11-21 14:51:54.686140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5449b2a706d8'
down_revision: Union[str, None] = 'feac743d4799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('standing_quantity', sa.Integer(), nullable=False))
    op.alter_column('orders', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('orders', 'standing_quantity')
    # ### end Alembic commands ###
