"""created instruments table

Revision ID: 54be4547e2f2
Revises: 82b059a250d9
Create Date: 2025-03-12 16:04:51.358307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54be4547e2f2"
down_revision: Union[str, None] = "82b059a250d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("instrument_id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("instrument", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("starting_price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("instrument_id"),
        sa.UniqueConstraint("instrument"),
        sa.UniqueConstraint("instrument_id"),
    )
    op.add_column(
        "market_data", sa.Column("instrument_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "market_data", "instruments", ["instrument_id"], ["instrument_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "market_data", type_="foreignkey")
    op.drop_column("market_data", "instrument_id")
    op.drop_table("instruments")
    # ### end Alembic commands ###
