"""added relationships in escrows table

Revision ID: 550d41f509eb
Revises: ea87b94b38ee
Create Date: 2025-07-18 10:18:15.559050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550d41f509eb'
down_revision: Union[str, None] = 'ea87b94b38ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
