"""added price field to order_events

Revision ID: 58b38a78bcc2
Revises: b6d95ecb7ece
Create Date: 2025-07-17 13:37:53.180686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b38a78bcc2'
down_revision: Union[str, None] = 'b6d95ecb7ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_events', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_events', 'price')
    # ### end Alembic commands ###
