"""renamed transaction_id to order_event_id

Revision ID: 7871f7a58d66
Revises: ca5aac87bf3a
Create Date: 2025-07-17 12:41:21.087186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7871f7a58d66'
down_revision: Union[str, None] = 'ca5aac87bf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_events', sa.Column('order_event_id', sa.UUID(), nullable=False))
    op.drop_column('order_events', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_events', sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('order_events', 'order_event_id')
    # ### end Alembic commands ###
