"""added closed at field to orders

Revision ID: 82b059a250d9
Revises: d965fb14cee8
Create Date: 2025-03-08 20:04:51.278514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b059a250d9'
down_revision: Union[str, None] = 'd965fb14cee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'closed_at')
    # ### end Alembic commands ###
