"""user relationships for orders and userwathlist tbale

Revision ID: 8c7422b53359
Revises: 53b6cca58e7a
Create Date: 2024-12-06 22:05:10.551914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7422b53359'
down_revision: Union[str, None] = '53b6cca58e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
