"""visible attribute for user table

Revision ID: 8fd93e2adf68
Revises: c2c7a146f9dd
Create Date: 2024-12-06 21:24:59.430050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd93e2adf68'
down_revision: Union[str, None] = 'c2c7a146f9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visible')
    # ### end Alembic commands ###
