"""added open_quantity field to orders table

Revision ID: 948d3eac4898
Revises: 550d41f509eb
Create Date: 2025-07-18 10:58:31.699440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948d3eac4898'
down_revision: Union[str, None] = '550d41f509eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('open_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'open_quantity')
    # ### end Alembic commands ###
