"""renamed field trade_id to order_id along with other changes

Revision ID: 9aa5cafe4e5b
Revises: 9d863c822a96
Create Date: 2025-02-26 20:37:04.663963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa5cafe4e5b'
down_revision: Union[str, None] = '9d863c822a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.UUID(), nullable=False))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('standing_quantity', sa.Integer(), nullable=False))
    op.drop_column('orders', 'trade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'standing_quantity')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###
