"""added fields

Revision ID: 9d34038621e0
Revises: 0fd66c8ea319
Create Date: 2024-10-31 16:54:59.397223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d34038621e0'
down_revision: Union[str, None] = '0fd66c8ea319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.UUID(), nullable=False))
    op.drop_column('orders', 'trade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###
