"""added field instrument to orders table

Revision ID: 9d863c822a96
Revises: b4940ca0594e
Create Date: 2025-02-26 18:27:49.995106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d863c822a96'
down_revision: Union[str, None] = 'b4940ca0594e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('instrument', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'instrument')
    # ### end Alembic commands ###
