"""added new fields to orders

Revision ID: a6d62cc1cbdb
Revises: c0a6c9c5598d
Create Date: 2025-03-02 16:38:00.834813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d62cc1cbdb'
down_revision: Union[str, None] = 'c0a6c9c5598d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('filled_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('realised_pnl', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('unrealised_pnl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'unrealised_pnl')
    op.drop_column('orders', 'realised_pnl')
    op.drop_column('orders', 'filled_price')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
