"""renamed transaction_type to event_type

Revision ID: b6d95ecb7ece
Revises: 7871f7a58d66
Create Date: 2025-07-17 12:41:50.307608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d95ecb7ece'
down_revision: Union[str, None] = '7871f7a58d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_events', sa.Column('event_type', sa.String(), nullable=False))
    op.drop_column('order_events', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_events', sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('order_events', 'event_type')
    # ### end Alembic commands ###
