"""added filled price field

Revision ID: be9a7d80a883
Revises: 5c6bf750bb35
Create Date: 2024-11-03 15:25:37.718550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9a7d80a883'
down_revision: Union[str, None] = '5c6bf750bb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('filled_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'filled_price')
    # ### end Alembic commands ###
