"""Added spot and futures boolean field in watchlist table

Revision ID: deafe50f9b4b
Revises: 05c93b13f41a
Create Date: 2025-01-09 10:55:33.183099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deafe50f9b4b'
down_revision: Union[str, None] = '05c93b13f41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'market_type',
               existing_type=postgresql.ENUM('SPOT', 'FUTURES', name='market_type'),
               nullable=False)
    op.add_column('watchlist_user', sa.Column('spot', sa.Boolean(), nullable=False))
    op.add_column('watchlist_user', sa.Column('futures', sa.Boolean(), nullable=False))
    op.add_column('watchlist_user', sa.Column('limit_order', sa.Boolean(), nullable=False))
    op.add_column('watchlist_user', sa.Column('market_order', sa.Boolean(), nullable=False))
    op.drop_column('watchlist_user', 'limit_orders')
    op.drop_column('watchlist_user', 'market_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_user', sa.Column('market_orders', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('watchlist_user', sa.Column('limit_orders', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('watchlist_user', 'market_order')
    op.drop_column('watchlist_user', 'limit_order')
    op.drop_column('watchlist_user', 'futures')
    op.drop_column('watchlist_user', 'spot')
    op.alter_column('orders', 'market_type',
               existing_type=postgresql.ENUM('SPOT', 'FUTURES', name='market_type'),
               nullable=True)
    # ### end Alembic commands ###
