"""Created order table and ensured UUIDs are stored as UUID

Revision ID: e5fdc9223d21
Revises: f95bed2c41d7
Create Date: 2024-10-30 00:57:13.713042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fdc9223d21'
down_revision: Union[str, None] = 'f95bed2c41d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'BUY_LIMIT', 'SELL_LIMIT', name='order_type'), nullable=False),
    sa.Column('dollar_amount', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.CheckConstraint('dollar_amount > 0', name='dollar_amount_minimum_value'),
    sa.CheckConstraint('limit_price > 0', name='limit_price_minimum_value'),
    sa.CheckConstraint('stop_loss > 0', name='stop_loss_minimum_value'),
    sa.CheckConstraint('take_profit > 0', name='take_profit_minimum_value'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
