"""add realised and unrealisd pnl fields

Revision ID: ed0728233e80
Revises: 5449b2a706d8
Create Date: 2024-11-21 21:17:41.120176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0728233e80'
down_revision: Union[str, None] = '5449b2a706d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('realised_pnl', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('unrealised_pnl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'unrealised_pnl')
    op.drop_column('orders', 'realised_pnl')
    # ### end Alembic commands ###
